export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const SELECTED_PICA = 'SELECTED_PICA';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const TOGGLE_BAG_ICON = 'TOGGLE_BAG_ICON';
export const HIDDE_DROP_DOWN_CART = 'HIDDE_DROP_DOWN_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART';
export const TOGGLE_TO_ORDER_CONFIRMATION = 'TOGGLE_TO_ORDER_CONFIRMATION';
export const CLEAR_CART = 'CLEAR_CART';

//address
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const ADDRESS_INPUT_CHANGE = 'ADDRESS_INPUT_CHANGE';
export const ADD_ADDRESS_ERRORS = 'ADD_ADDRESS_ERRORS';

//authorithation
export const TOOGLE_LOGIN_MODAL = 'TOOGLE_AUTH_MODAL';
export const LOGIN_INPUT_CHANGE = ' AUTH_INPUT_CHANGE';
export const TOGGLE_SIGNUP_MODAL = 'TOGGLE_SIGNUP_MODAL';
export const SIGN_UP_INPUT_CHANG = 'SIGN_UP_INPUT_CHANGE';
export const AUTH_ERROR = ' AUTH_ERROR';
